// СГЕНЕРИРОВАНО `npm run api:fields` из docs/api-v5.md. Руками не править —
// перезапишется; расхождение с снимком ловит api-fields.unit.test.ts.
//
// Значения FieldNames для каждого метода v5. Хендлер берёт набор целиком
// (`[...API_FIELDS.ads.AdFieldEnum]`) или объявляет подмножество типом
// `FieldOf<"ads", "AdFieldEnum">[]` — тогда имя не из перечисления не компилируется.
export const API_FIELDS = {
  adextensions: {
    AdExtensionFieldEnum: ["Associated", "Id", "State", "Status", "StatusClarification", "Type"],
    CalloutFieldEnum: ["CalloutText"]
  },
  adgroups: {
    AdGroupFieldEnum: [
      "CampaignId",
      "Id",
      "Name",
      "NegativeKeywordSharedSetIds",
      "NegativeKeywords",
      "RegionIds",
      "RestrictedRegionIds",
      "ServingStatus",
      "Status",
      "Subtype",
      "TrackingParams",
      "Type"
    ],
    DynamicTextAdGroupFieldEnum: [
      "AutotargetingCategories",
      "AutotargetingSettings",
      "DomainUrl",
      "DomainUrlProcessingStatus"
    ],
    DynamicTextFeedAdGroupFieldEnum: [
      "AutotargetingCategories",
      "AutotargetingSettings",
      "FeedId",
      "Source",
      "SourceProcessingStatus",
      "SourceType"
    ],
    MobileAppAdGroupFieldEnum: [
      "AppAvailabilityStatus",
      "AppIconModeration",
      "AppOperatingSystemType",
      "StoreUrl",
      "TargetCarrier",
      "TargetDeviceType",
      "TargetOperatingSystemVersion"
    ],
    SmartAdGroupFieldEnum: ["AdBodySource", "AdTitleSource", "FeedId"],
    TextAdGroupFeedParamsFieldEnum: ["FeedCategoryIds", "FeedId"],
    UnifiedAdGroupFieldEnum: ["OfferRetargeting"]
  },
  adimages: {
    AdImageFieldEnum: ["AdImageHash", "Associated", "Name", "OriginalUrl", "PreviewUrl", "Subtype", "Type"]
  },
  ads: {
    AdFieldEnum: [
      "AdCategories",
      "AdGroupId",
      "AgeLabel",
      "CampaignId",
      "Id",
      "State",
      "Status",
      "StatusClarification",
      "Subtype",
      "Type"
    ],
    CpcVideoAdBuilderAdFieldEnum: [
      "AutogeneratedErirAdDescription",
      "Creative",
      "ErirAdDescription",
      "Href",
      "TurboPageId",
      "TurboPageModeration"
    ],
    CpmBannerAdBuilderAdFieldEnum: [
      "AutogeneratedErirAdDescription",
      "Creative",
      "ErirAdDescription",
      "Href",
      "TrackingPixels",
      "TurboPageId",
      "TurboPageModeration"
    ],
    CpmVideoAdBuilderAdFieldEnum: [
      "AutogeneratedErirAdDescription",
      "Creative",
      "ErirAdDescription",
      "Href",
      "TrackingPixels",
      "TurboPageId",
      "TurboPageModeration"
    ],
    DynamicTextAdFieldEnum: [
      "AdExtensions",
      "AdImageHash",
      "AdImageModeration",
      "SitelinkSetId",
      "SitelinksModeration",
      "Text",
      "VCardId",
      "VCardModeration"
    ],
    ListingAdFieldEnum: [
      "AdExtensions",
      "BusinessId",
      "DefaultTexts",
      "FeedFilterConditions",
      "FeedId",
      "FeedProcessingStatus",
      "SitelinkSetId",
      "SitelinksModeration",
      "TextSources",
      "TitleSources"
    ],
    MobileAppAdBuilderAdFieldEnum: ["AutogeneratedErirAdDescription", "Creative", "ErirAdDescription", "TrackingUrl"],
    MobileAppAdFieldEnum: [
      "Action",
      "AdImageHash",
      "AdImageModeration",
      "AutogeneratedErirAdDescription",
      "ErirAdDescription",
      "Features",
      "Text",
      "Title",
      "TrackingUrl",
      "VideoExtension"
    ],
    MobileAppCpcVideoAdBuilderAdFieldEnum: [
      "AutogeneratedErirAdDescription",
      "Creative",
      "ErirAdDescription",
      "TrackingUrl"
    ],
    MobileAppImageAdFieldEnum: ["AdImageHash", "AutogeneratedErirAdDescription", "ErirAdDescription", "TrackingUrl"],
    ResponsiveAdFieldEnum: [
      "AdExtensions",
      "AdImages",
      "BusinessId",
      "DisplayDomain",
      "DisplayUrlPath",
      "DisplayUrlPathModeration",
      "ErirAdDescription",
      "Href",
      "PriceExtension",
      "SitelinkSetId",
      "SitelinksModeration",
      "Texts",
      "Titles",
      "VideoExtensions"
    ],
    ShoppingAdFieldEnum: [
      "AdExtensions",
      "BusinessId",
      "DefaultTexts",
      "FeedFilterConditions",
      "FeedId",
      "FeedProcessingStatus",
      "SitelinkSetId",
      "SitelinksModeration",
      "TextSources",
      "TitleSources"
    ],
    SmartAdBuilderAdFieldEnum: ["Creative"],
    TextAdBuilderAdFieldEnum: [
      "AutogeneratedErirAdDescription",
      "Creative",
      "ErirAdDescription",
      "FinalUrl",
      "Href",
      "TurboPageId",
      "TurboPageModeration"
    ],
    TextAdFieldEnum: [
      "AdExtensions",
      "AdImageHash",
      "AdImageModeration",
      "AutogeneratedErirAdDescription",
      "BusinessId",
      "DisplayDomain",
      "DisplayUrlPath",
      "DisplayUrlPathModeration",
      "ErirAdDescription",
      "FinalUrl",
      "Href",
      "Mobile",
      "PreferVCardOverBusiness",
      "SitelinkSetId",
      "SitelinksModeration",
      "Text",
      "Title",
      "Title2",
      "TurboPageId",
      "TurboPageModeration",
      "VCardId",
      "VCardModeration",
      "VideoExtension"
    ],
    TextAdPriceExtensionFieldEnum: ["OldPrice", "Price", "PriceCurrency", "PriceQualifier"],
    TextImageAdFieldEnum: [
      "AdImageHash",
      "AutogeneratedErirAdDescription",
      "ErirAdDescription",
      "FinalUrl",
      "Href",
      "TurboPageId",
      "TurboPageModeration"
    ]
  },
  agencyclients: {
    AgencyClientFieldEnum: [
      "AccountQuality",
      "Archived",
      "AvailableAdGroupTypes",
      "AvailableCampaignTypes",
      "Bonuses",
      "ClientId",
      "ClientInfo",
      "CountryId",
      "CreatedAt",
      "Currency",
      "ForbiddenPlatform",
      "Grants",
      "Login",
      "Notification",
      "OverdraftSumAvailable",
      "Phone",
      "Representatives",
      "Restrictions",
      "Settings",
      "Type",
      "VatRate"
    ]
  },
  audiencetargets: {
    AudienceTargetFieldEnum: [
      "AdGroupId",
      "CampaignId",
      "ContextBid",
      "Id",
      "InterestId",
      "RetargetingListId",
      "State",
      "StrategyPriority"
    ]
  },
  bidmodifiers: {
    AdGroupAdjustmentFieldEnum: ["BidModifier"],
    BidModifierFieldEnum: ["AdGroupId", "CampaignId", "Id", "Level", "Type"],
    DemographicsAdjustmentFieldEnum: ["Age", "BidModifier", "Enabled", "Gender"],
    DesktopAdjustmentFieldEnum: ["BidModifier"],
    DesktopOnlyAdjustmentFieldEnum: ["BidModifier"],
    IncomeGradeAdjustmentFieldEnum: ["BidModifier", "Enabled", "Grade"],
    MobileAdjustmentFieldEnum: ["BidModifier", "OperatingSystemType"],
    RegionalAdjustmentFieldEnum: ["BidModifier", "Enabled", "RegionId"],
    RetargetingAdjustmentFieldEnum: ["Accessible", "BidModifier", "Enabled", "RetargetingConditionId"],
    SerpLayoutAdjustmentFieldEnum: ["BidModifier", "Enabled", "SerpLayout"],
    SmartAdAdjustmentFieldEnum: ["BidModifier"],
    SmartTvAdjustmentFieldEnum: ["BidModifier"],
    TabletAdjustmentFieldEnum: ["BidModifier", "OperatingSystemType"],
    VideoAdjustmentFieldEnum: ["BidModifier"]
  },
  bids: {
    BidFieldEnum: [
      "AdGroupId",
      "AuctionBids",
      "AutotargetingSearchBidIsAuto",
      "Bid",
      "CampaignId",
      "CompetitorsBids",
      "ContextBid",
      "ContextCoverage",
      "CurrentSearchPrice",
      "KeywordId",
      "MinSearchPrice",
      "SearchPrices",
      "ServingStatus",
      "StrategyPriority"
    ]
  },
  businesses: {
    BusinessFieldEnum: [
      "Address",
      "HasOffice",
      "Id",
      "InternalUrl",
      "IsPublished",
      "MergedIds",
      "Name",
      "Phone",
      "ProfileUrl",
      "Rubric",
      "Urls"
    ]
  },
  campaigns: {
    CampaignFieldEnum: [
      "BlockedIps",
      "ClientInfo",
      "Currency",
      "DailyBudget",
      "EndDate",
      "ExcludedSites",
      "Funds",
      "Id",
      "Name",
      "NegativeKeywords",
      "Notification",
      "RepresentedBy",
      "SourceId",
      "StartDate",
      "State",
      "Statistics",
      "Status",
      "StatusClarification",
      "StatusPayment",
      "TimeTargeting",
      "TimeZone",
      "Type"
    ],
    CpmBannerCampaignFieldEnum: ["BiddingStrategy", "CounterIds", "FrequencyCap", "Settings", "VideoTarget"],
    DynamicTextCampaignFieldEnum: [
      "AttributionModel",
      "BiddingStrategy",
      "CanBeUsedAsPackageBiddingStrategySource",
      "CounterIds",
      "NegativeKeywordSharedSetIds",
      "PackageBiddingStrategy",
      "PlacementTypes",
      "PriorityGoals",
      "Settings",
      "TrackingParams"
    ],
    DynamicTextCampaignSearchStrategyPlacementTypesFieldEnum: ["DynamicPlaces", "ProductGallery", "SearchResults"],
    MobileAppCampaignFieldEnum: [
      "BiddingStrategy",
      "CanBeUsedAsPackageBiddingStrategySource",
      "NegativeKeywordSharedSetIds",
      "PackageBiddingStrategy",
      "Settings",
      "WeeklyBudgetRollover"
    ],
    SmartCampaignFieldEnum: [
      "AttributionModel",
      "BiddingStrategy",
      "CanBeUsedAsPackageBiddingStrategySource",
      "CounterId",
      "PackageBiddingStrategy",
      "PriorityGoals",
      "Settings",
      "TrackingParams"
    ],
    TextCampaignFieldEnum: [
      "AttributionModel",
      "BiddingStrategy",
      "CanBeUsedAsPackageBiddingStrategySource",
      "CounterIds",
      "NegativeKeywordSharedSetIds",
      "PackageBiddingStrategy",
      "PriorityGoals",
      "RelevantKeywords",
      "Settings",
      "TrackingParams",
      "WeeklyBudgetRollover"
    ],
    TextCampaignSearchStrategyPlacementTypesFieldEnum: ["DynamicPlaces", "ProductGallery", "SearchResults"],
    UnifiedCampaignFieldEnum: [
      "AttributionModel",
      "BiddingStrategy",
      "CanBeUsedAsPackageBiddingStrategySource",
      "CounterIds",
      "NegativeKeywordSharedSetIds",
      "PackageBiddingStrategy",
      "PriorityGoals",
      "Settings",
      "TrackingParams",
      "WeeklyBudgetRollover"
    ],
    UnifiedCampaignPackageBiddingStrategyPlatformsFieldEnum: [
      "DynamicPlaces",
      "Maps",
      "Network",
      "ProductGallery",
      "SearchOrganizationList",
      "SearchResult"
    ],
    UnifiedCampaignSearchStrategyPlacementTypesFieldEnum: [
      "DynamicPlaces",
      "Maps",
      "ProductGallery",
      "SearchOrganizationList",
      "SearchResults"
    ]
  },
  changes: {
    CheckFieldEnum: ["AdGroupIds", "AdIds", "CampaignIds", "CampaignsStat"]
  },
  clients: {
    ClientFieldEnum: [
      "AccountQuality",
      "Archived",
      "AvailableAdGroupTypes",
      "AvailableCampaignTypes",
      "Bonuses",
      "ClientId",
      "ClientInfo",
      "CountryId",
      "CreatedAt",
      "Currency",
      "ForbiddenPlatform",
      "Grants",
      "Login",
      "Notification",
      "OverdraftSumAvailable",
      "Phone",
      "Representatives",
      "Restrictions",
      "Settings",
      "Type",
      "VatRate"
    ]
  },
  creatives: {
    CpcVideoCreativeFieldEnum: ["Duration"],
    CpmVideoCreativeFieldEnum: ["Duration"],
    CreativeFieldEnum: [
      "Associated",
      "Height",
      "Id",
      "IsAdaptive",
      "Name",
      "PreviewUrl",
      "ThumbnailUrl",
      "Type",
      "Width"
    ],
    SmartCreativeFieldEnum: ["BusinessType", "CreativeGroupId", "CreativeGroupName"],
    VideoExtensionCreativeFieldEnum: ["Duration"]
  },
  dictionaries: {
    GeoRegionFieldEnum: ["GeoRegionId", "GeoRegionName", "ParentGeoRegionNames"]
  },
  dynamictextadtargets: {
    WebpageFieldEnum: [
      "AdGroupId",
      "Bid",
      "CampaignId",
      "ConditionType",
      "Conditions",
      "ContextBid",
      "Id",
      "Name",
      "State",
      "StatusClarification",
      "StrategyPriority"
    ]
  },
  feeds: {
    FeedFieldEnum: [
      "BusinessType",
      "CampaignIds",
      "FilterSchema",
      "Id",
      "Name",
      "NumberOfItems",
      "NumberOfListings",
      "SourceType",
      "Status",
      "TitleAndTextSources",
      "UpdatedAt"
    ],
    FileFeedFieldEnum: ["Filename"],
    UrlFeedFieldEnum: ["Login", "RemoveUtmTags", "Url"]
  },
  keywordbids: {
    KeywordBidFieldEnum: ["AdGroupId", "CampaignId", "KeywordId", "ServingStatus", "StrategyPriority"],
    KeywordBidNetworkFieldEnum: ["Bid", "Coverage"],
    KeywordBidSearchFieldEnum: ["AuctionBids", "AutotargetingSearchBidIsAuto", "Bid"]
  },
  keywords: {
    KeywordFieldEnum: [
      "AdGroupId",
      "AutotargetingBrandOptions",
      "AutotargetingCategories",
      "AutotargetingSearchBidIsAuto",
      "Bid",
      "CampaignId",
      "ContextBid",
      "Id",
      "Keyword",
      "Productivity",
      "ServingStatus",
      "State",
      "StatisticsNetwork",
      "StatisticsSearch",
      "Status",
      "StrategyPriority",
      "UserParam1",
      "UserParam2"
    ]
  },
  keywordsresearch: {
    HasSearchVolumeFieldEnum: ["AllDevices", "Desktops", "Keyword", "MobilePhones", "RegionIds", "Tablets"]
  },
  leads: {
    LeadFieldEnum: ["Data", "Id", "SubmittedAt", "TurboPageId", "TurboPageName"]
  },
  negativekeywordsharedsets: {
    NegativeKeywordSharedSetFieldEnum: ["Associated", "Id", "Name", "NegativeKeywords"]
  },
  retargetinglists: {
    RetargetingListFieldEnum: [
      "AvailableForTargetsInAdGroupTypes",
      "Description",
      "Id",
      "IsAvailable",
      "Name",
      "Rules",
      "Scope",
      "Type"
    ]
  },
  sitelinks: {
    SitelinkFieldEnum: ["Description", "Href", "Title", "TurboPageId"],
    SitelinksSetFieldEnum: ["Id", "Sitelinks"]
  },
  smartadtargets: {
    SmartAdTargetFieldEnum: [
      "AdGroupId",
      "Audience",
      "AvailableItemsOnly",
      "AverageCpa",
      "AverageCpc",
      "CampaignId",
      "ConditionType",
      "Conditions",
      "Id",
      "Name",
      "State",
      "StrategyPriority"
    ]
  },
  strategies: {
    StrategyAverageCpaFieldEnum: [
      "AverageCpa",
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "GoalId",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpaMultipleGoalsFieldEnum: [
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpaPerCampaignFieldEnum: [
      "AverageCpa",
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "GoalId",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpaPerFilterFieldEnum: [
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "FilterAverageCpa",
      "GoalId",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpcFieldEnum: [
      "AverageCpc",
      "BudgetType",
      "CustomPeriodBudget",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpcPerCampaignFieldEnum: [
      "AverageCpc",
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "WeeklySpendLimit"
    ],
    StrategyAverageCpcPerFilterFieldEnum: [
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "FilterAverageCpc",
      "WeeklySpendLimit"
    ],
    StrategyAverageCrrFieldEnum: [
      "BudgetType",
      "Crr",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "GoalId",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyFieldEnum: ["AttributionModel", "CounterIds", "Id", "Name", "PriorityGoals", "StatusArchived", "Type"],
    StrategyMaximumClicksFieldEnum: [
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyMaximumConversionRateFieldEnum: [
      "BidCeiling",
      "BudgetType",
      "CustomPeriodBudget",
      "GoalId",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyMaxProfitFieldEnum: [
      "BudgetType",
      "CustomPeriodBudget",
      "ExplorationBudget",
      "WeeklyBudgetRollover",
      "WeeklySpendLimit"
    ],
    StrategyPayForConversionCrrFieldEnum: ["BudgetType", "Crr", "CustomPeriodBudget", "GoalId", "WeeklySpendLimit"],
    StrategyPayForConversionFieldEnum: ["BudgetType", "Cpa", "CustomPeriodBudget", "GoalId", "WeeklySpendLimit"],
    StrategyPayForConversionMultipleGoalsFieldEnum: ["BudgetType", "CustomPeriodBudget", "WeeklySpendLimit"],
    StrategyPayForConversionPerCampaignFieldEnum: [
      "BudgetType",
      "Cpa",
      "CustomPeriodBudget",
      "GoalId",
      "WeeklySpendLimit"
    ],
    StrategyPayForConversionPerFilterFieldEnum: [
      "BudgetType",
      "Cpa",
      "CustomPeriodBudget",
      "GoalId",
      "WeeklySpendLimit"
    ]
  },
  turbopages: {
    TurboPageFieldEnum: ["BoundWithHref", "Href", "Id", "Name", "PreviewHref", "TurboSiteHref"]
  },
  vcards: {
    VCardFieldEnum: [
      "Apartment",
      "Building",
      "CampaignId",
      "City",
      "CompanyName",
      "ContactEmail",
      "ContactPerson",
      "Country",
      "ExtraMessage",
      "House",
      "Id",
      "InstantMessenger",
      "MetroStationId",
      "Ogrn",
      "Phone",
      "PointOnMap",
      "Street",
      "WorkTime"
    ]
  },
  "general.xsd": {
    AutotargetingBrandOptionsFieldEnum: ["WithAdvertiserBrand", "WithCompetitorsBrand", "WithoutBrands"],
    AutotargetingCategoriesFieldEnum: ["Accessory", "Alternative", "Broader", "Exact", "Narrow"]
  }
} as const

// Внутренний: наружу ходит только FieldOf — сервис задаётся его первым параметром.
type ApiService = keyof typeof API_FIELDS

// Значение одного перечисления: FieldOf<"campaigns", "CampaignFieldEnum">.
export type FieldOf<
  S extends ApiService,
  E extends keyof (typeof API_FIELDS)[S]
> = (typeof API_FIELDS)[S][E] extends readonly (infer Value)[] ? Value : never
